# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getCoreNum <- function() {
    .Call('Emcdf_getCoreNum', PACKAGE = 'Emcdf')
}

build <- function(x_in, num) {
    .Call('Emcdf_build', PACKAGE = 'Emcdf', x_in, num)
}

compute <- function(p_in, a) {
    .Call('Emcdf_compute', PACKAGE = 'Emcdf', p_in, a)
}

biemcdf_output <- function(x, y, is_tie) {
    .Call('Emcdf_biemcdf_output', PACKAGE = 'Emcdf', x, y, is_tie)
}

single <- function(data, a) {
    .Call('Emcdf_single', PACKAGE = 'Emcdf', data, a)
}

single1 <- function(data, a) {
    .Call('Emcdf_single1', PACKAGE = 'Emcdf', data, a)
}

single2 <- function(data, a) {
    .Call('Emcdf_single2', PACKAGE = 'Emcdf', data, a)
}

single3 <- function(data, a) {
    .Call('Emcdf_single3', PACKAGE = 'Emcdf', data, a)
}

single4 <- function(data, a) {
    .Call('Emcdf_single4', PACKAGE = 'Emcdf', data, a)
}

single5 <- function(data, a) {
    .Call('Emcdf_single5', PACKAGE = 'Emcdf', data, a)
}

SortByX <- function(x, y) {
    .Call('Emcdf_SortByX', PACKAGE = 'Emcdf', x, y)
}

